kind: Service
apiVersion: v1
metadata:
  name: node-app-service
spec:
  type: LoadBalancer
  selector:
    app: node-app 
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 8080
    nodePort: 31110

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  labels:
    app: node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app 
    spec:
      containers:
      - name: node-app
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8080